[2023-01-17T15:37:18.218+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark.spark_job manual__2023-01-17T15:36:23.765759+00:00 [queued]>
[2023-01-17T15:37:18.247+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark.spark_job manual__2023-01-17T15:36:23.765759+00:00 [queued]>
[2023-01-17T15:37:18.248+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T15:37:18.249+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-17T15:37:18.250+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T15:37:18.298+0000] {taskinstance.py:1383} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2023-01-17 15:36:23.765759+00:00
[2023-01-17T15:37:18.305+0000] {standard_task_runner.py:54} INFO - Started process 21 to run task
[2023-01-17T15:37:18.316+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'spark', 'spark_job', 'manual__2023-01-17T15:36:23.765759+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmp44mda_gl']
[2023-01-17T15:37:18.320+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask spark_job
[2023-01-17T15:37:18.324+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/Airflow/dags/spark_dag.py
[2023-01-17T15:37:24.977+0000] {task_command.py:384} INFO - Running <TaskInstance: spark.spark_job manual__2023-01-17T15:36:23.765759+00:00 [running]> on host sparksparkjob-f42d9f429eba4fb6806b5ead30fb11e4
[2023-01-17T15:37:30.266+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spark
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T15:36:23.765759+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-17T15:36:23.765759+00:00
[2023-01-17T15:37:30.291+0000] {base.py:71} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-17T15:37:30.293+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master 10.96.144.83 :7077 --name arrow-spark spark-app.py
[2023-01-17T15:37:30.628+0000] {spark_submit.py:495} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-17T15:37:35.495+0000] {spark_submit.py:495} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2023-01-17T15:37:35.496+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:975)
[2023-01-17T15:37:35.497+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:238)
[2023-01-17T15:37:35.497+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2023-01-17T15:37:35.498+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2023-01-17T15:37:35.498+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2023-01-17T15:37:35.498+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2023-01-17T15:37:35.499+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2023-01-17T15:37:35.499+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2023-01-17T15:37:35.500+0000] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-01-17T15:37:35.587+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master 10.96.144.83 :7077 --name arrow-spark spark-app.py. Error code is: 1.
[2023-01-17T15:37:35.605+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=spark, task_id=spark_job, execution_date=20230117T153623, start_date=20230117T153718, end_date=20230117T153735
[2023-01-17T15:37:35.650+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task spark_job (Cannot execute: spark-submit --master 10.96.144.83 :7077 --name arrow-spark spark-app.py. Error code is: 1.; 21)
[2023-01-17T15:37:35.727+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-17T15:37:35.777+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
